#!/usr/bin/env sh
echo ""
echo "커밋 메시지 검사 시작"
npx --no-install commitlint --edit "$1" || {
  echo "📝 커밋 메시지 규칙:"
  echo "[개발자 영문 이름], [브랜치명(chore,feat,hotfix)]: [구현내용] #[관련 이슈 번호]"
  echo "예시: byungchan, chore: 프로젝트 초기 환경 설정 및 테스트 #1"
  echo ""
  exit 1 # 비정상 종료 코드 반환
}
echo "커밋 메시지가 규칙에 맞습니다!"
